apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linker-frontend-ingress
  namespace: linker
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx

  tls:
    - hosts:
        - media-fidigitals.space
      secretName: media-tls-secret

  rules:
    - host: media-fidigitals.space
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
